name: Docs Lint and Link Check
on:
  pull_request:
    paths:
      - 'docs/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Lint markdown
        run: npm run lint
      - name: Check links
        run: npm run check-links
