name: Publish Docs to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Copy docs
        run: |
          mkdir _site
          cp -r docs/* _site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
